import type { DesignTheme } from "@/types";

export const defaultTheme: DesignTheme = {
  id: "default",
  name: "スタンダード",
  description: "シンプルで使いやすい基本テーマ",
  preview: { bg: "#f8f9fa", card: "#ffffff", accent: "#ec4899" },
  variables: {
    "--bg-page": "#f8f9fa",
    "--bg-card": "rgba(255,255,255,0.55)",
    "--bg-header": "rgba(0,0,0,0.8)",
    "--bg-nav": "#ffffff",
    "--bg-modal": "#ffffff",
    "--bg-input": "#ffffff",
    "--bg-skeleton": "#f3f4f6",
    "--text-primary": "#000000",
    "--text-secondary": "#4b5563",
    "--text-muted": "#6b7280",
    "--text-heading": "#000000",
    "--border-card": "#f3f4f6",
    "--border-input": "#e5e7eb",
    "--border-divider": "#f3f4f6",
    "--shadow-card": "0 1px 2px 0 rgba(0,0,0,0.05)",
    "--shadow-card-hover": "0 4px 6px -1px rgba(0,0,0,0.1)",
    "--radius-card": "1rem",
    "--radius-button": "0.75rem",
    "--radius-input": "0.75rem",
    "--font-family":
      '"Hiragino Sans","Hiragino Kaku Gothic ProN","Noto Sans JP",sans-serif',
    "--backdrop-blur": "blur(12px)",
    "--nav-border-top": "1px solid #e5e7eb",
    "--header-text": "#ffffff",
    "--header-accent-bg": "rgba(255,255,255,0.2)",
    "--nav-bg": "rgba(0,0,0,0.75)",
    "--nav-tab-bg": "rgba(0,0,0,0.6)",
    "--nav-text": "#ffffff",
    "--nav-text-inactive": "rgba(255,255,255,0.45)",
    "--nav-accent-bg": "rgba(255,255,255,0.2)",
    "--pw-bg": "#0a0a0a",
    "--pw-title": "#ffffff",
    "--pw-tab-inactive-bg": "#e5e5e5",
    "--pw-tab-inactive-text": "#6b6b6b",
  },
};
