import type { DesignTheme } from "@/types";

export const koreanTheme: DesignTheme = {
  id: "korean",
  name: "ミニマル",
  description: "余白を活かした洗練されたデザイン",
  preview: { bg: "#fafafa", card: "#ffffff", accent: "#1a1a1a" },
  variables: {
    "--bg-page": "#fafafa",
    "--bg-card": "rgba(255,255,255,0.55)",
    "--bg-header": "#ffffff",
    "--bg-nav": "#ffffff",
    "--bg-modal": "#ffffff",
    "--bg-input": "#fafafa",
    "--bg-skeleton": "#f5f5f5",
    "--text-primary": "#1a1a1a",
    "--text-secondary": "#555555",
    "--text-muted": "#888888",
    "--text-heading": "#0a0a0a",
    "--border-card": "#e0e0e0",
    "--border-input": "#e0e0e0",
    "--border-divider": "#eeeeee",
    "--shadow-card": "none",
    "--shadow-card-hover": "0 1px 3px rgba(0,0,0,0.08)",
    "--radius-card": "0.25rem",
    "--radius-button": "0.25rem",
    "--radius-input": "0.25rem",
    "--font-family":
      '"Noto Serif JP","Hiragino Mincho ProN","Yu Mincho",serif',
    "--backdrop-blur": "none",
    "--header-text": "#0a0a0a",
    "--header-accent-bg": "#f0f0f0",
    "--nav-border-top": "1px solid #e0e0e0",
    "--nav-bg": "#ffffff",
    "--nav-tab-bg": "#f5f5f5",
    "--nav-text": "#0a0a0a",
    "--nav-text-inactive": "#999999",
    "--nav-accent-bg": "#f0f0f0",
    "--pw-bg": "#f0f0f0",
    "--pw-title": "#1a1a1a",
    "--pw-tab-inactive-bg": "#e5e5e5",
    "--pw-tab-inactive-text": "#555555",
  },
};
